---
- name: Automatic Repository Sync
  hosts: localhost  # Assuming you're running this playbook locally on the Ansible control node
  
  tasks:
    - name: Update Git repository
      git:
        repo: https://github.com/SaifRehman/ansible-microshift.git  # Replace with your Git repository URL
        dest: /path/to/your/local/repository  # Specify the local directory where the repository should be cloned/pulled
        version: main  # Specify the branch or commit hash if needed
        force: yes  # Ensure any local changes are overridden
        update: yes  # Ensure the repository is updated

    - name: Display git update result
      debug:
        var: ansible_git_module_results  # Display the result of the git update operation
