---
- name: "install centos vm with httpd configured"
  hosts: microshift
  vars_files:
    - vars.yml
  tasks:
    - name: "Create Namespace {{ namespacedefined }}"
      kubernetes.core.k8s:
        state: present
        template: namespace.yml.j2