---
- name: "create namespace"
  hosts: microshift
  vars_files:
    - vars.yml
  tasks:
    - name: Create namespace YAML from template
      template:
        src: namespace.yml.j2
        dest: /tmp/namespace.yaml
    - name: "Create Namespace {{ namespacedefined }}"
      shell: kubectl apply -f /tmp/namespace.yaml